// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAczRtenUD7Ky5uac0tK_vcyPTle7m9d_g',
    appId: '1:856867087553:web:bd934f97a2c18e56f32040',
    messagingSenderId: '856867087553',
    projectId: 'vet-loksewa-46d0f',
    authDomain: 'vet-loksewa-46d0f.firebaseapp.com',
    storageBucket: 'vet-loksewa-46d0f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTyUBsvqi7XQCbuznQk4-_m7cbmAMAAwo',
    appId: '1:856867087553:android:8af3e022573e6165f32040',
    messagingSenderId: '856867087553',
    projectId: 'vet-loksewa-46d0f',
    storageBucket: 'vet-loksewa-46d0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFweZTF6EpvoKkhuV-avKdzmtZRq9j43s',
    appId: '1:856867087553:ios:904f85836dd766e2f32040',
    messagingSenderId: '856867087553',
    projectId: 'vet-loksewa-46d0f',
    storageBucket: 'vet-loksewa-46d0f.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFweZTF6EpvoKkhuV-avKdzmtZRq9j43s',
    appId: '1:856867087553:ios:904f85836dd766e2f32040',
    messagingSenderId: '856867087553',
    projectId: 'vet-loksewa-46d0f',
    storageBucket: 'vet-loksewa-46d0f.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAczRtenUD7Ky5uac0tK_vcyPTle7m9d_g',
    appId: '1:856867087553:web:9e7c8715581872aef32040',
    messagingSenderId: '856867087553',
    projectId: 'vet-loksewa-46d0f',
    authDomain: 'vet-loksewa-46d0f.firebaseapp.com',
    storageBucket: 'vet-loksewa-46d0f.firebasestorage.app',
  );
}
